version: 2
updates:
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: pytest-django
    versions:
    - 4.1.0
  - dependency-name: pillow
    versions:
    - 6.2.0
